services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bridge
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8090:90"
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:90"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
